// app/projects/[slug]/directory/page.tsx
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { PageShell } from "@/components/pe/page-shell";
import { PageKicker } from "@/components/pe/page-kicker";
import { UserPlus, Mail } from "lucide-react";
import { getProject, getDirectory } from "@/lib/queries";
import type { DirectoryEntry } from "@/data/types";

function getInitials(name: string) {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase();
}

function getStatusColor(
  status: "Admin" | "Member" | "Guest-Admin" | "Guest" | "Reviewer" | "Owner" | "AHJ"
) {
  switch (status) {
    case "Admin":
      return "green";
    case "Owner":
      return "blue";
    case "Member":
      return "blue";
    case "Reviewer":
      return "purple";
    case "Guest-Admin":
      return "purple";
    case "Guest":
      return "amber";
    case "AHJ":
      return "red";
    default:
      return "gray";
  }
}

export default async function DirectoryPage({
  params,
}: {
  params: { slug: string };
}) {
  const project = await getProject(params.slug);
  if (!project) {
    notFound();
  }

  const directory = await getDirectory(params.slug);

  // Group by organization
  const grouped = directory.reduce(
    (acc, entry) => {
      if (!acc[entry.organization]) {
        acc[entry.organization] = [];
      }
      acc[entry.organization].push(entry);
      return acc;
    },
    {} as Record<string, DirectoryEntry[]>
  );

  const orgs = Object.keys(grouped).sort();
  const uniqueOrgs = new Set(directory.map((d) => d.organization));

  return (
    <PageShell>
      <div className="mb-8">
        <div className="flex items-start justify-between gap-6">
          <div>
            <PageKicker>{project.title}</PageKicker>
            <h1 className="mt-1 text-3xl font-bold text-pe-body">People</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              {directory.length} people · {uniqueOrgs.size} organizations
            </p>
          </div>
          <Button disabled variant="secondary">
            <UserPlus className="mr-2 h-4 w-4" />
            Invite
          </Button>
        </div>
      </div>

      <div className="space-y-8">
        {orgs.map((org) => (
          <div key={org}>
            <h2 className="text-base font-semibold text-pe-body mb-4">
              {org}
            </h2>

            <div className="grid gap-4 grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
              {grouped[org].map((person) => (
                <Card
                  key={person.id}
                  className="p-4 hover:shadow-md transition-shadow"
                >
                  <div className="flex items-start gap-3 mb-3">
                    <Avatar className="h-10 w-10 shrink-0">
                      <AvatarFallback className="text-sm font-semibold">
                        {getInitials(person.name)}
                      </AvatarFallback>
                    </Avatar>

                    <div className="flex-1">
                      <div className="font-semibold text-sm text-pe-body">
                        {person.name}
                      </div>
                      <div className="text-xs text-muted-foreground">
                        {person.role}
                      </div>
                    </div>
                  </div>

                  <Badge
                    variant={getStatusColor(person.status)}
                    className="mb-3 w-fit text-xs"
                  >
                    {person.status}
                  </Badge>

                  {person.email && (
                    <a
                      href={`mailto:${person.email}`}
                      className="flex items-center gap-2 text-xs text-muted-foreground hover:text-pe-body transition-colors"
                    >
                      <Mail className="h-3.5 w-3.5" />
                      <span className="truncate">{person.email}</span>
                    </a>
                  )}
                </Card>
              ))}
            </div>
          </div>
        ))}
      </div>
    </PageShell>
  );
}

// src/routes/projects/[slug]/directory/+page.svelte
<script lang="ts">
  import { Mail, Search, UserRound } from '@lucide/svelte';
  import PageShell from '$lib/components/PageShell.svelte';
  import StatusPill from '$lib/components/StatusPill.svelte';
  import { initialsFor } from '$lib/utils';

  let { data } = $props();
  let query = $state('');
  const filtered = $derived(data.directory.filter((person) => `${person.name} ${person.organization} ${person.role}`.toLowerCase().includes(query.toLowerCase())));
</script>

<svelte:head>
  <title>Directory | {data.project?.title}</title>
</svelte:head>

<PageShell>
  <div class="mb-6 flex flex-wrap items-end justify-between gap-4">
    <div>
      <p class="text-xs font-black uppercase tracking-[0.16em] text-pe-green-dark">{data.project?.title}</p>
      <h1 class="mt-2 text-3xl font-black text-pe-body">Directory</h1>
      <p class="mt-2 text-sm leading-6 text-pe-sub">Client, design, AHJ, reviewer, and Pueblo Electric project contacts.</p>
    </div>
    <div class="flex w-full items-center gap-2 rounded-lg border border-black/8 bg-white px-3 py-2 sm:w-auto sm:min-w-72">
      <Search size={16} class="text-pe-sub" />
      <input bind:value={query} class="w-full bg-transparent text-sm outline-none" placeholder="Search people" />
    </div>
  </div>

  <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
    {#each filtered as person}
      <article class="panel lift rounded-xl p-5">
        <div class="flex items-start gap-3">
          <div class="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-pe-green text-sm font-black text-white">
            {initialsFor({ full_name: person.name, email: person.email ?? null })}
          </div>
          <div class="min-w-0">
            <h2 class="truncate text-base font-black text-pe-body">{person.name}</h2>
            <p class="text-sm text-pe-sub">{person.role}</p>
            <p class="text-sm font-semibold text-pe-body">{person.organization}</p>
          </div>
        </div>
        <div class="mt-4 flex flex-wrap items-center gap-2">
          <StatusPill label={person.status} />
          {#if person.email}
            <a class="btn btn-secondary min-h-8 px-2 text-xs" href={`mailto:${person.email}`}>
              <Mail size={14} />
              Email
            </a>
          {:else}
            <span class="inline-flex items-center gap-1 text-xs font-bold text-pe-sub"><UserRound size={14} />Portal user</span>
          {/if}
        </div>
      </article>
    {/each}
  </section>
</PageShell>
