// app/projects/[slug]/page.tsx
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  Calendar,
  Folder,
  FileCheck2,
  MessageSquare,
  Newspaper,
  Users,
  ChevronRight,
  Clock,
} from "lucide-react";
import { PageShell } from "@/components/pe/page-shell";
import { GlassCard } from "@/components/pe/glass-card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { CardTitle, CardDescription } from "@/components/ui/card";
import { getProject, getSchedule, getUpdates } from "@/lib/queries";
import type { ScheduleActivity } from "@/data/types";

const TODAY = new Date("2026-04-21");
const LOOK_AHEAD_DAYS = 21;

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
  });
}

function getWeekLabel(date: Date): string {
  const start = new Date(date);
  start.setDate(start.getDate() - start.getDay());
  const end = new Date(start);
  end.setDate(end.getDate() + 6);

  return `${start.toLocaleDateString("en-US", { month: "short", day: "numeric" })} – ${end.toLocaleDateString("en-US", { month: "short", day: "numeric" })}`;
}

function groupActivitiesByWeek(
  activities: ScheduleActivity[],
  today: Date,
  days: number
): [string, ScheduleActivity[]][] {
  const endDate = new Date(today);
  endDate.setDate(endDate.getDate() + days);

  const filtered = activities.filter((a) => {
    const start = new Date(a.startDate);
    return start >= today && start <= endDate;
  });

  const grouped = new Map<string, ScheduleActivity[]>();
  filtered.forEach((activity) => {
    const start = new Date(activity.startDate);
    const weekLabel = getWeekLabel(start);
    if (!grouped.has(weekLabel)) {
      grouped.set(weekLabel, []);
    }
    grouped.get(weekLabel)!.push(activity);
  });

  return Array.from(grouped.entries());
}

export default async function ProjectHomePage({
  params,
}: {
  params: { slug: string };
}) {
  const project = await getProject(params.slug);
  if (!project) {
    notFound();
  }

  const [scheduleActivities, updates] = await Promise.all([
    getSchedule(params.slug),
    getUpdates(params.slug),
  ]);

  const nextMilestoneDate = new Date(project.nextMilestoneDate);
  const daysUntil = Math.ceil(
    (nextMilestoneDate.getTime() - TODAY.getTime()) / (1000 * 60 * 60 * 24)
  );

  const weeklyActivities = groupActivitiesByWeek(scheduleActivities, TODAY, LOOK_AHEAD_DAYS);

  const recentUpdates = updates.slice(0, 6);

  const quickNavTiles = [
    {
      label: "Files",
      icon: Folder,
      href: `/projects/${params.slug}/files`,
      count: undefined,
    },
    {
      label: "Schedule",
      icon: Calendar,
      href: `/projects/${params.slug}/schedule`,
      count: undefined,
    },
    {
      label: "Submittals",
      icon: FileCheck2,
      href: `/projects/${params.slug}/submittals`,
      count: project.openSubmittals,
    },
    {
      label: "Updates",
      icon: Newspaper,
      href: `/projects/${params.slug}/updates`,
      count: undefined,
    },
    {
      label: "Chat",
      icon: MessageSquare,
      href: `/projects/${params.slug}/chat`,
      count: undefined,
    },
    {
      label: "Directory",
      icon: Users,
      href: `/projects/${params.slug}/directory`,
      count: undefined,
    },
  ];

  return (
    <PageShell>
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <GlassCard>
            <div className="space-y-2 mb-4">
              <div className="text-xs uppercase tracking-[0.1em] text-muted-foreground font-semibold">
                Next milestone
              </div>
              <h3 className="text-xl font-semibold text-pe-body">
                {project.nextMilestone}
              </h3>
            </div>
            <div className="flex items-baseline gap-3 mb-4">
              <span className="text-3xl font-bold text-pe-green">
                {nextMilestoneDate.toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                })}
              </span>
              <span className="text-sm text-muted-foreground">
                T-minus{" "}
                <span className="font-semibold text-pe-body">{daysUntil}</span>{" "}
                {daysUntil === 1 ? "day" : "days"}
              </span>
            </div>
            <Button variant="outline" asChild>
              <Link href={`/projects/${params.slug}/schedule`}>
                View on schedule <ChevronRight className="h-4 w-4" />
              </Link>
            </Button>
          </GlassCard>

          <GlassCard>
            <div className="mb-4">
              <CardTitle className="text-base">3-week look-ahead</CardTitle>
            </div>
            <div className="space-y-4">
              {weeklyActivities.length > 0 ? (
                weeklyActivities.map(([weekLabel, activities]) => (
                  <div key={weekLabel}>
                    <div className="text-xs uppercase tracking-[0.1em] text-muted-foreground font-semibold mb-2">
                      {weekLabel}
                    </div>
                    <div className="space-y-2">
                      {activities.slice(0, 3).map((activity) => (
                        <div
                          key={activity.id}
                          className="text-sm bg-white/50 rounded p-2.5"
                        >
                          <div className="flex items-start gap-2">
                            <Badge variant={activity.status} className="text-[10px] flex-shrink-0 mt-0.5">
                              {activity.phase.split(" ")[0]}
                            </Badge>
                            <div className="flex-1 min-w-0">
                              <p className="font-medium text-pe-body truncate">
                                {activity.title}
                              </p>
                              <p className="text-xs text-muted-foreground">
                                {formatDate(activity.startDate)} –{" "}
                                {formatDate(activity.endDate)} · {activity.owner}
                              </p>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-sm text-muted-foreground">
                  No activities scheduled in the next 3 weeks
                </p>
              )}
            </div>
          </GlassCard>

          <GlassCard>
            <div className="mb-4">
              <CardTitle className="text-base">Activity feed</CardTitle>
            </div>
            <div className="space-y-3">
              {recentUpdates.map((update) => (
                <div
                  key={update.id}
                  className="text-sm bg-white/50 rounded p-3 border border-border/40"
                >
                  <div className="flex items-start gap-2.5">
                    <Avatar className="h-7 w-7 flex-shrink-0 mt-0.5">
                      <AvatarFallback className="text-[10px]">
                        {update.author
                          .split(" ")
                          .map((n) => n[0])
                          .join("")}
                      </AvatarFallback>
                    </Avatar>
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-pe-body leading-tight">
                        {update.title}
                      </p>
                      <p className="text-xs text-muted-foreground mt-0.5">
                        {update.author} · {update.postedTime}
                      </p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </GlassCard>
        </div>

        <div className="space-y-6">
          <div className="grid grid-cols-2 gap-3">
            {quickNavTiles.map(({ label, icon: Icon, href, count }) => (
              <Link
                key={label}
                href={href}
                className="group"
              >
                <GlassCard className="h-full cursor-pointer transition-all hover:shadow-md">
                  <div className="flex flex-col items-center gap-2 text-center">
                    <Icon className="h-5 w-5 text-pe-green" />
                    <span className="text-xs font-medium text-pe-body">
                      {label}
                    </span>
                    {count !== undefined && count > 0 && (
                      <Badge variant="amber" className="text-[9px]">
                        {count} open
                      </Badge>
                    )}
                  </div>
                </GlassCard>
              </Link>
            ))}
          </div>

          <GlassCard>
            <div className="mb-3">
              <CardTitle className="text-sm">People</CardTitle>
              <CardDescription className="text-xs">
                Project team members
              </CardDescription>
            </div>
            <div className="flex gap-1.5 mb-3">
              {[1, 2, 3, 4, 5].map((i) => (
                <Avatar key={i} className="h-7 w-7 border border-border">
                  <AvatarFallback className="text-[9px]">
                    {String.fromCharCode(64 + i)}
                  </AvatarFallback>
                </Avatar>
              ))}
            </div>
            <Button
              variant="link"
              size="sm"
              asChild
              className="h-auto p-0 text-xs"
            >
              <Link href={`/projects/${params.slug}/directory`}>
                +8 more members →
              </Link>
            </Button>
          </GlassCard>
        </div>
      </div>
    </PageShell>
  );
}

// src/routes/projects/[slug]/+page.svelte
<script lang="ts">
  import { CalendarDays, FileText, FolderOpen, MessageSquare, Users } from '@lucide/svelte';
  import PageShell from '$lib/components/PageShell.svelte';
  import StatusPill from '$lib/components/StatusPill.svelte';
  import { formatDate, relativeTime } from '$lib/utils';

  let { data } = $props();
  const project = $derived(data.project);
  const openSubmittals = $derived(data.submittals.filter((item) => !['Approved', 'Rejected'].includes(item.status)));
  const openRfis = $derived(data.rfis.filter((item) => item.status === 'Open'));
  const nextActivities = $derived(data.schedule.slice(0, 5));
</script>

<svelte:head>
  <title>{project.title} | Pueblo Electric Project Portal</title>
</svelte:head>

<PageShell>
  <section class="mb-6 grid gap-5 lg:grid-cols-[1fr_360px]">
    <div class="glass rounded-xl p-6">
      <p class="text-xs font-black uppercase tracking-[0.16em] text-pe-green-dark">{project.number}</p>
      <h1 class="mt-2 max-w-4xl text-3xl font-black leading-tight text-pe-body">{project.title}</h1>
      <p class="mt-3 text-sm leading-6 text-pe-sub">{project.address} &middot; {project.owner}</p>
      <div class="mt-5 flex flex-wrap items-center gap-3">
        <StatusPill label={project.status} />
        <span class="rounded-full bg-black/5 px-3 py-1 text-xs font-bold text-pe-sub">Target {formatDate(project.targetComplete || project.nextMilestoneDate)}</span>
      </div>
      <div class="mt-6">
        <div class="mb-2 flex justify-between text-xs font-bold uppercase tracking-[0.08em] text-pe-sub">
          <span>Project completion</span>
          <span>{project.completionPercent}%</span>
        </div>
        <div class="h-2.5 overflow-hidden rounded-full bg-black/8">
          <div class="h-full rounded-full bg-pe-green" style={`width:${project.completionPercent}%`}></div>
        </div>
      </div>
    </div>

    <div class="panel rounded-xl p-5">
      <h2 class="text-base font-black text-pe-body">Next milestone</h2>
      <p class="mt-2 text-xl font-black text-pe-body">{project.nextMilestone || 'Not set'}</p>
      <p class="mt-2 text-sm text-pe-sub">{formatDate(project.nextMilestoneDate, { weekday: 'long', month: 'long', day: 'numeric' })}</p>
      <a class="btn btn-secondary mt-5 w-full" href={`/projects/${data.slug}/schedule`}>
        <CalendarDays size={16} />
        View schedule
      </a>
    </div>
  </section>

  <section class="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
    <a class="panel lift rounded-xl p-5" href={`/projects/${data.slug}/submittals`}>
      <FileText class="text-pe-green" size={24} />
      <div class="mt-4 text-3xl font-black text-pe-body">{openSubmittals.length}</div>
      <div class="text-sm font-bold text-pe-sub">Open submittals</div>
    </a>
    <a class="panel lift rounded-xl p-5" href={`/projects/${data.slug}/rfis`}>
      <MessageSquare class="text-pe-green" size={24} />
      <div class="mt-4 text-3xl font-black text-pe-body">{openRfis.length}</div>
      <div class="text-sm font-bold text-pe-sub">Open RFIs</div>
    </a>
    <a class="panel lift rounded-xl p-5" href={`/projects/${data.slug}/files`}>
      <FolderOpen class="text-pe-green" size={24} />
      <div class="mt-4 text-3xl font-black text-pe-body">{data.files.length}</div>
      <div class="text-sm font-bold text-pe-sub">Drawings & specs</div>
    </a>
    <a class="panel lift rounded-xl p-5" href={`/projects/${data.slug}/directory`}>
      <Users class="text-pe-green" size={24} />
      <div class="mt-4 text-3xl font-black text-pe-body">{data.directory.length}</div>
      <div class="text-sm font-bold text-pe-sub">Team members</div>
    </a>
  </section>

  <section class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
    <div class="panel rounded-xl p-5">
      <div class="mb-4 flex items-center justify-between">
        <h2 class="text-base font-black text-pe-body">Upcoming work</h2>
        <a class="text-sm font-bold text-pe-green-dark" href={`/projects/${data.slug}/schedule`}>Schedule</a>
      </div>
      <div class="space-y-3">
        {#each nextActivities as item}
          <div class="flex items-center justify-between gap-3 rounded-lg border border-black/8 bg-white/72 p-3">
            <div>
              <div class="text-sm font-black text-pe-body">{item.title}</div>
              <div class="text-xs text-pe-sub">{item.phase} &middot; {item.owner}</div>
            </div>
            <div class="text-right text-xs font-bold text-pe-sub">{formatDate(item.startDate)} - {formatDate(item.endDate)}</div>
          </div>
        {/each}
      </div>
    </div>

    <div class="panel rounded-xl p-5">
      <div class="mb-4 flex items-center justify-between">
        <h2 class="text-base font-black text-pe-body">Latest updates</h2>
        <a class="text-sm font-bold text-pe-green-dark" href={`/projects/${data.slug}/updates`}>Updates</a>
      </div>
      <div class="space-y-3">
        {#each data.updates.slice(0, 4) as update}
          <article class="rounded-lg border border-black/8 bg-white/72 p-3">
            <div class="mb-1 flex items-center justify-between gap-3">
              <h3 class="text-sm font-black text-pe-body">{update.title}</h3>
              <span class="text-xs font-bold text-pe-sub">{relativeTime(update.postedDate)}</span>
            </div>
            <p class="line-clamp-2 text-sm leading-6 text-pe-sub">{update.body}</p>
          </article>
        {/each}
      </div>
    </div>
  </section>
</PageShell>
