// components/pe/page-shell.tsx
import { cn } from "@/lib/utils";

/** Centered, max-width page body. Used under the AppHeader. */
export function PageShell({
  children,
  className,
}: {
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <main className={cn("mx-auto w-full max-w-7xl px-6 py-8", className)}>
      {children}
    </main>
  );
}

// src/lib/components/PageShell.svelte
<script lang="ts">
  let {
    wide = false,
    flush = false,
    children
  }: { wide?: boolean; flush?: boolean; children: import('svelte').Snippet } = $props();
</script>

<main class={`page-enter mx-auto w-full ${wide ? 'max-w-[1480px]' : 'max-w-7xl'} ${flush ? '' : 'px-3 py-5 sm:px-6 sm:py-8 lg:px-8'}`}>
  {@render children()}
</main>
